parser:
    service: markdown.parser.sundown
sundown:
    extensions:
        fenced_code_blocks: true
        no_intra_emphasis: true
        tables: true
        autolink: true
        strikethrough: true
        lax_html_blocks: true
        space_after_headers: true
        superscript: true
    render_flags:
        filter_html:          false
        no_images:            false
        no_links:             false
        no_styles:            false
        safe_links_only:      false
        with_toc_data:        true
        hard_wrap:            false
        xhtml:                false