parser:
    service: markdown.parser.sundown
sundown:
    extensions:
        fenced_code_blocks: true
        no_intra_emphasis: true
        tables: true
        autolink: true
        strikethrough: true
        lax_html_blocks: true
        space_after_headers: true
        superscript: true