services:
    symfony_slate.toc_data:
        class: Soltys\Bundle\SoltysSlateBundle\Twig\TocDataExtension
        tags:
            - { name: twig.extension }
    symfony_slate.markdown:
        class: Soltys\Bundle\SoltysSlateBundle\Twig\MarkdownExtension
        tags:
            - { name: twig.extension }