services:
    symfony_slate.toc_data:
        class: Soltys\Bundle\SoltysSlateBundle\Twig\TocDataExtension
        tags: [twig.extension]
    symfony_slate.markdown:
        class: Soltys\Bundle\SoltysSlateBundle\Twig\MarkdownExtension
        tags: [twig.extension]